# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: "137.0.7151.119"
          install-chromedriver: true
      - name: Install python dependencies
        env:
          PIP_REQUIREMENTS: mitmproxy/src/python/requirements-ci.lock.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f $PIP_REQUIREMENTS ]; then pip install -r $PIP_REQUIREMENTS; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=200 --statistics
      - name: Get installed playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(grep playwright mitmproxy/src/python/requirements-test.lock.txt)" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright dependencies
        run: |
          playwright install --with-deps
      - name: Test with pytest
        run: |
          pytest --tracing=retain-on-failure
      - name: Commit new obfuscated files
        if: failure() && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python mitmproxy/src/python/save_obfuscated_code.py
          
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.name "github-actions"
            git config --local user.email "github-actions@github.com"
            git switch -c obfuscated-files || true
            git add .
            git commit -m "Obfuscated files" || echo "No changes to commit"
            git push -u origin obfuscated-files --force || echo "Failed to push changes"
            gh pr create --title "Obfuscated files" --body "Update obfuscated files" --base main --head obfuscated-files || echo "Failed to create PR"
            gh pr merge --squash --delete-branch "obfuscated-files" || echo "Failed to enable auto-merge"
          else
            echo "No changes detected, skipping PR creation"
          fi

      - name: Archive output artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            output/*
